function [EEG, status] = conditional_cleanline(EEG, opts)
%CONDITIONAL_CLEANLINE Apply cleanline at >=500 Hz; no-op on the 100 Hz L100 dataset unless forced.
%   [EEG, status] = hbn.conditional_cleanline(EEG, opts) runs pop_cleanline
%   with the reference-pipeline parameters when opts.RunCleanline is true
%   OR EEG.srate >= 500. At 100 Hz sampling the 60 Hz US line fundamental
%   is already above the 50 Hz Nyquist, removed by the 500 -> 100 Hz
%   anti-alias downsample that produced the local BDF files; 120 and 180
%   Hz were never in-band. The step is therefore a no-op at 100 Hz and is
%   skipped unless opts.RunCleanline forces it.
%
%   status is one of "applied" or "skipped_nyquist".
    arguments
        EEG struct
        opts struct
    end
    runIt = opts.RunCleanline || (EEG.srate >= 500);
    if ~runIt
        status = "skipped_nyquist";
        return
    end
    try
        EEG = pop_cleanline(EEG, ...
            'bandwidth', 2, ...
            'chanlist', 1:EEG.nbchan, ...
            'computepower', 1, ...
            'linefreqs', opts.LineNoiseHz, ...
            'normSpectrum', 0, ...
            'p', 0.05, ...
            'pad', 2, ...
            'plotfigures', 0, ...
            'scanforlines', 1, ...
            'sigtype', 'Channels', ...
            'tau', 100, ...
            'verb', 1, ...
            'winsize', 4, ...
            'winstep', 1, ...
            'newversion', true);
    catch ME
        error("hbn:conditional_cleanline:pop_cleanline_failed", ...
            "pop_cleanline failed: %s (%s)", ME.message, ME.identifier);
    end
    status = "applied";
end
